package agents.events;

public enum EventType {
    AGENT_CREATED,
    AGENT_DIED,
    AGENT_REPLACED,
    PLAN_RECEIVED,
    PART_RECEIVED,
    PART_CREATED,
    PRODUCT_ASSEMBLED,
    ORDER_COMPLETED,
    PRODUCTS_RECEIVED,
    SYSTEM_SHUTDOWN
}
